In [1]:
print('ldoa')

ldoa

In [9]:
import pandas as pd

In [20]:
df = pd.read_excel(r"C:\Users\vikas kumar\Downloads\Churn_Unclean_Project.xlsx")
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [17]:
import os

for file in os.listdir(r"C:\Users\vikas kumar\Downloads"):
    if file.endswith(".xlsx"):
        print(file)

14GRLPS3637D1ZL_4A_132024.xlsx
14GRLPS3637D1ZL_4A_142024.xlsx
14GRLPS3637D1ZL_4A_152024.xlsx
14GRLPS3637D1ZL_4A_162024 (1).xlsx
14GRLPS3637D1ZL_4A_162024.xlsx
Category_Icons.xlsx
Churn_Unclean_Project.xlsx
ecommerce_sales_data.xlsx

In [22]:
import pandas as pd

df = pd.read_excel(r"C:\Users\vikas kumar\Downloads\Churn_Unclean_Project.xlsx")

df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [21]:
df = pd.read_excel('Churn_Unclean_Project.xlsx')

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Churn_Unclean_Project.xlsx'

In [24]:
pwd

'C:\\Users\\Vikas Kumar'